# Generated by Django 5.0.7 on 2024-07-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_blogpost_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='slag',
            new_name='slug',
        ),
    ]
