# Generated by Django 5.0.7 on 2024-08-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_slag_blogpost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.URLField()),
                ('datetime', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
    ]
